### ISSUE TITLE
Using bot for managing threads

### ISSUE THREAD

**Issue by Padmanabh82** [reactiflux/reactibot#137] opened 2021-12-22 11:19 UTC
As everyone knows, we are using threads in help-js. So, i think we should relay on bots instead of humans like bot will automatically start a thread when someone sends a message, bot will close a thread on inactivity or on !close command and pin active threads or questions and unpin after closed (but bot will only work after @vcarl and @nickmccurdy shift bot on discord 13)

**Comment by nickmccurdy** [comment] 2021-12-22 12:58
This seems like a duplicate of #134 which we're already planning.

**Closed** 2021-12-22 12:58 UTC
Labels: duplicate
