### ISSUE TITLE
Improve anti-scam

### ISSUE THREAD

**Issue by Padmanabh82** [reactiflux/reactibot#187] opened 2022-02-11 12:20 UTC
Aa, so.. i am here with a new issue for improving our scam/spam dection system. Here is a famous tech YouTuber named [ThioJoe](https://youtube.com/c/ThioJoe) has made a small [program](https://github.com/ThioJoe/YT-Spammer-Purge) in python in his vedios [part1](https://youtu.be/-vOakOgYLUI) [part2](https://youtu.be/2tRppXW_aKo) for removing spams and scam in yt's  comments. So, i think we can or should implement his anti-scam system in js in our bot. Now i am waiting for staff's opinions

**Comment by vcarl** [comment] 2022-02-28 20:23
Dupe of #117

**Closed by vcarl** 2022-02-28 20:23 UTC

**Comment by Padmanabh82** [comment] 2022-03-02 03:10
@vcarl is it same ??? Did you checked code ???
